version: '3.1'

services:
  master_db:
    image: mysql:latest
    container_name: master_db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --server-id=1
      - --log-bin=mysql-bin
      - --binlog-format=row
      - --gtid-mode=ON
      - --log-slave-updates=ON
      - --enforce-gtid-consistency=ON
    restart: always
    environment:
      MYSQL_DATABASE: master
      MYSQL_ROOT_PASSWORD: master-password
    ports:
      - "3306:3306"

  slave_db:
    image: mysql:latest
    container_name: slave_db
    command:
      - --default-authentication-plugin=mysql_native_password
      - --server-id=2
      - --relay-log-index=slave-relay-bin.index
      - --relay-log=slave-relay-bin
      - --log-slave-updates=ON
      - --gtid-mode=ON
      - --enforce-gtid-consistency=ON
      - --master-info-repository=TABLE
      - --relay-log-info-repository=TABLE
      - --slave-skip-errors=all
    restart: always
    environment:
      MYSQL_DATABASE: slave
      MYSQL_ROOT_PASSWORD: slave-password
    depends_on:
      - master_db
    ports:
      - "3307:3306"